# Generated by Django 5.0.2 on 2024-02-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('current_grade', models.CharField(max_length=100)),
                ('date_of_first_appointment', models.DateField()),
                ('date_of_present_appointment', models.DateField()),
                ('highest_qualification', models.CharField(max_length=100)),
                ('senior_junior', models.CharField(choices=[('Senior', 'Senior'), ('Junior', 'Junior')], max_length=10)),
                ('years_of_current_dept', models.IntegerField()),
                ('profession', models.CharField(max_length=100)),
                ('fulltime_staff', models.BooleanField(default=True)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('supervisor_name', models.CharField(max_length=100)),
                ('supervisor_grade', models.CharField(max_length=100)),
                ('supervisor_staff_id', models.CharField(max_length=20)),
            ],
        ),
    ]
