# Generated by Django 4.2.2 on 2024-02-20 08:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0004_attendancelog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
