# Generated by Django 5.0.2 on 2024-02-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0007_alter_customer_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='highest_qualification',
            new_name='Department',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='date_of_first_appointment',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='date_of_present_appointment',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='supervisor_grade',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='supervisor_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='supervisor_staff_id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='years_of_current_dept',
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_national',
            field=models.CharField(choices=[('Staff', 'Staff'), ('National Service', 'National Service')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
