# Generated by Django 4.2.2 on 2024-03-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0009_remove_staff_fulltime_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='Department',
        ),
        migrations.AddField(
            model_name='staff',
            name='Directorate',
            field=models.CharField(choices=[('POLICY, PLANNING, BUDGETING, MONITORING AND EVALUATION', 'POLICY, PLANNING, BUDGETING, MONITORING AND EVALUATION'), ('HUMAN RESOURCE MANAGEMENT AND DEVELOPMENT ', 'HUMAN RESOURCE MANAGEMENT AND DEVELOPMENT'), ('RESEARCH STATISTICS AND INFORMATION MANAGEMENT', 'RESEARCH STATISTICS AND INFORMATION MANAGEMENT'), ('GENERAL ADMINISTRATION\xa0', 'GENERAL ADMINISTRATION\xa0'), ('FINANCE', 'FINANCE')], default='FINANCE', max_length=100),
            preserve_default=False,
        ),
    ]
