# Generated by Django 4.2.2 on 2024-03-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0010_remove_staff_department_staff_directorate'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
