# Generated by Django 4.2.2 on 2024-03-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0011_attendancelog_image_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancelog',
            old_name='sign_in_time',
            new_name='signtime',
        ),
        migrations.RemoveField(
            model_name='attendancelog',
            name='sign_out_time',
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='action',
            field=models.CharField(default='sign in', max_length=100),
            preserve_default=False,
        ),
    ]
