# Generated by Django 4.2.2 on 2024-03-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_app', '0012_rename_sign_in_time_attendancelog_signtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancelog',
            old_name='signtime',
            new_name='sign_in_time',
        ),
        migrations.RemoveField(
            model_name='attendancelog',
            name='action',
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='sign_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
